/**
 * vm/evidencePack.ts — the artifact you hand an interviewer.
 *
 * Everything needed for this already existed and none of it could leave the
 * machine. Lab Plan knew which lessons were complete and why, the ticket queue
 * knew which tickets had passed review and on what checks, and the audit log
 * held the entries behind both. A learner finishing the course had no way to
 * show any of it to anybody.
 *
 * "I did an IAM course" and "here is the estate I built, the tickets I closed,
 * the reviews that passed them, and the log entries behind each claim" are
 * different sentences in an interview. This produces the second one.
 *
 * Markdown rather than PDF, deliberately. A PDF needs a rendering library —
 * megabytes of dependency to produce a file nobody can edit — while Markdown
 * opens in any editor, pastes into a CV, renders on GitHub, and prints to PDF
 * from the browser when a PDF is what somebody wants. The print stylesheet in
 * the Lab Plan window covers that case.
 *
 * Nothing here is generated by a model. Every line is read out of the services,
 * because a portfolio whose contents were written by an LLM is exactly the
 * thing an interviewer is trying to see past.
 */
import { PRODUCT } from '@/config/product';
import { COMPANY } from '@/config/company';
import { VM_HOST } from '@/config/vmHost';
import { computeProgress } from './labProgress';
import type { LessonProgress } from './labProgress';
import { reviewTicketSync } from './ticketReview';
import type { VmServices } from './session';
import { MockAuditLog } from '@/services';
import type { AuditEvent, Ticket } from '@/domain';

/** How many log lines to quote per task before it stops being readable. */
const MAX_EVIDENCE_LINES = 6;

function stamp(at: number): string {
  return new Date(at).toISOString().replace('T', ' ').slice(0, 19);
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/** The log entries behind one lesson, newest last. */
function evidenceFor(s: VmServices, entry: LessonProgress): AuditEvent[] {
  const wanted = new Set(entry.actions);
  return s.audit.events.filter((e) => wanted.has(e.action)).slice(-MAX_EVIDENCE_LINES);
}

function auditLine(s: VmServices, e: AuditEvent): string {
  // Resolve ids to names where possible: "user-a4f1" proves nothing to a
  // reader, and the point of the pack is to be readable by somebody else.
  const name = (id?: string): string => {
    if (!id) return '';
    const user = s.dir.listUsers().find((u) => u.id === id);
    if (user) return user.username;
    const group = s.dir.listGroups().find((g) => g.id === id);
    if (group) return group.name;
    const ou = s.dir.listOus().find((o) => o.id === id);
    if (ou) return ou.name;
    return id;
  };
  const target = name(e.targetId);
  const subject = e.subjectId ? ` → ${name(e.subjectId)}` : '';
  const note = e.note ? ` — ${e.note}` : '';
  return `${stamp(e.at)}  ${e.action}  ${target}${subject}${note}`.trimEnd();
}

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(' | ')} |`;
  const rule = `| ${headers.map(() => '---').join(' | ')} |`;
  const body = rows.map((r) => `| ${r.join(' | ')} |`).join('\n');
  return rows.length === 0 ? `${head}\n${rule}` : `${head}\n${rule}\n${body}`;
}

/** The estate as it stands, which is the thing that was built. */
function estateSection(s: VmServices): string {
  const ous = s.dir.listOus();
  const groups = s.dir.listGroups();
  const users = s.dir.listUsers();
  const staff = users.filter((u) => u.username !== 'admin' && !u.username.startsWith('svc-'));

  const lines = [
    '## The estate',
    '',
    `Built on \`${VM_HOST.name}\`, domain \`${COMPANY.domain}\`.`,
    '',
    table(
      ['Object', 'Count', 'Detail'],
      [
        [
          'Organisational units',
          String(ous.length),
          ous.length ? ous.map((o) => o.name).join(', ') : '—',
        ],
        [
          'Security groups',
          String(groups.length),
          groups.length ? groups.map((g) => g.name).join(', ') : '—',
        ],
        ['Accounts', String(users.length), `${staff.length} staff, ${users.length - staff.length} built-in or service`],
        [
          'Disabled accounts',
          String(users.filter((u) => u.status === 'disabled').length),
          'Offboarded during the exercise',
        ],
      ],
    ),
  ];

  const pim = s.pim?.list() ?? [];
  if (pim.length > 0) {
    const standing = s.pim?.standingPrivilege().length ?? 0;
    lines.push(
      '',
      `**Privileged access.** ${pim.length} assignment(s), ${standing} of them standing. ` +
        (standing === 0
          ? 'No permanent privilege remains, which is the state the PIM chapter asks for.'
          : 'Permanent privilege is still held, which a reviewer would ask about.'),
    );
  }

  const tenants = Object.values(s.cloud ?? {}).filter((t) => t.isConnected());
  if (tenants.length > 0) {
    lines.push(
      '',
      `**Cloud.** Connected to ${tenants.map((t) => t.vendor.label).join(' and ')}; ` +
        `${tenants.reduce((n, t) => n + t.list().length, 0)} object(s) synchronised.`,
    );
  }

  return lines.join('\n');
}

/** The curriculum, and what proves each completed task. */
function workSection(s: VmServices): string {
  const progress = computeProgress(s);
  const out: string[] = ['## Work completed', ''];

  out.push(
    table(
      ['#', 'Area', 'Complete', 'Tasks'],
      progress.chapters.map((c, i) => [
        String(i + 1),
        c.chapter.title.replace(/^\d+\s·\s/, ''),
        `${c.percent}%`,
        `${c.lessons.filter((l) => l.state === 'done').length} of ${c.lessons.length}`,
      ]),
    ),
    '',
  );

  for (const chapter of progress.chapters) {
    const done = chapter.lessons.filter((l) => l.state === 'done');
    if (done.length === 0) continue;

    out.push(`### ${chapter.chapter.title}`, '');
    for (const entry of done) {
      out.push(`#### ${entry.lesson.title}`, '');
      out.push(`**Objective.** ${entry.lesson.objective}`, '');
      out.push(`**What was done.** ${entry.evidence}`, '');
      // The manual's `verify` is an instruction for checking the work, not a
      // record of what was found -- it describes the starting state. Labelled
      // as a finding it read as a flat contradiction of the evidence line
      // above it, which in a document handed to an interviewer is worse than
      // omitting it.
      out.push(`**How to check it.** ${entry.lesson.verify}`, '');

      const events = evidenceFor(s, entry);
      if (events.length > 0) {
        out.push('**From the audit log:**', '', '```');
        for (const e of events) out.push(auditLine(s, e));
        out.push('```', '');
      }
    }
  }

  const outstanding = progress.chapters
    .flatMap((c) => c.lessons)
    .filter((l) => l.state !== 'done');
  if (outstanding.length > 0) {
    // Stating what is unfinished is what makes the finished part credible.
    out.push('### Still outstanding', '');
    out.push(
      table(
        ['Task', 'State', 'What remains'],
        outstanding.map((l) => [
          l.lesson.title,
          l.state === 'in-progress' ? 'In progress' : 'Not started',
          l.outstanding,
        ]),
      ),
      '',
    );
  }

  return out.join('\n');
}

/** Tickets closed, and the review that let each one close. */
function ticketSection(s: VmServices): string {
  const resolved = s.tickets.list().filter((t) => t.status === 'resolved');
  const out: string[] = ['## Tickets resolved', ''];

  if (resolved.length === 0) {
    out.push('No tickets have been resolved yet.', '');
    return out.join('\n');
  }

  const breached = resolved.filter((t) => t.slaBreachedAt !== undefined).length;
  out.push(
    `${resolved.length} ticket(s) closed. ` +
      (breached === 0
        ? 'All within their response target.'
        : `${breached} missed their response target.`),
    '',
    table(
      ['Subject', 'Kind', 'Priority', 'Within target'],
      resolved.map((t: Ticket) => [
        t.subject,
        t.kind,
        t.priority,
        t.slaBreachedAt === undefined ? 'Yes' : 'No',
      ]),
    ),
    '',
  );

  // Re-run the review so the pack states the verdict rather than remembering
  // one: a stored verdict could have been recorded before later changes undid
  // the work, and this reflects the estate as it is now.
  //
  // Against a scratch audit log, not the real one. reviewTicketSync records
  // every check it runs, so reviewing here would write dozens of entries into
  // the trail the pack is reporting on -- and generating the document twice
  // would produce two different documents, each containing the evidence of
  // the last one being generated.
  const deps = { dir: s.dir, audit: new MockAuditLog(), pim: s.pim, cloud: s.cloud };
  out.push('### What each ticket was checked against', '');
  for (const t of resolved.slice(0, 12)) {
    const review = reviewTicketSync(t, deps, 'system' as never);
    out.push(`**${t.subject}** — ${review.passed ? 'all checks pass' : 'checks now failing'}`, '');
    for (const check of review.checks) {
      out.push(`- ${check.passed ? '✓' : '✗'} **${check.label}** — ${check.detail}`);
    }
    out.push('');
  }

  return out.join('\n');
}

/** The whole log, so a reader can audit the claims above rather than trust them. */
function appendixSection(s: VmServices): string {
  const events = s.audit.events;
  const out = [
    '## Appendix — full audit trail',
    '',
    `${events.length} event(s) recorded during this exercise.`,
    '',
    '```',
  ];
  for (const e of events) out.push(auditLine(s, e));
  out.push('```', '');
  return out.join('\n');
}

export interface PackOptions {
  /** The signed-in account, named on the cover. */
  operator?: string;
  /** Leave the appendix out for a short version. */
  includeAppendix?: boolean;
}

/**
 * Build the pack.
 *
 * Read-only with respect to the services, which took a fix to be true: the
 * ticket reviews run against a scratch audit log, because reviewTicketSync
 * records every check and would otherwise write its own working into the
 * trail being reported. Running this twice produces the same document.
 */
export function buildEvidencePack(s: VmServices, opts: PackOptions = {}): string {
  const progress = computeProgress(s);
  const operator = opts.operator ?? 'the operator';

  const header = [
    `# Identity operations — evidence pack`,
    '',
    `**Operator.** ${operator}  `,
    `**Environment.** ${PRODUCT.name} on \`${VM_HOST.name}\`, domain \`${COMPANY.domain}\`  `,
    `**Generated.** ${today()}  `,
    `**Progress.** ${progress.percent}% — ${progress.done} of ${progress.total} tasks complete`,
    '',
    'Every claim in this document is derived from the directory, the audit log and the ' +
      'ticket reviews of a live workstation. Nothing was self-reported, and nothing was ' +
      'written by a language model.',
    '',
    '---',
    '',
  ].join('\n');

  const sections = [estateSection(s), workSection(s), ticketSection(s)];
  if (opts.includeAppendix !== false) sections.push(appendixSection(s));

  return `${header}${sections.join('\n\n')}\n`;
}

/** A filename that sorts by date and says what it is. */
export function packFilename(): string {
  return `iam-range-evidence-${today()}.md`;
}
